trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      containerRegistry: 'docker-hub-service-connection'
      repository: 'derya1123581321/assignment'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest


  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: 'latest'


  # - task: HelmDeploy@0
  #   inputs:
  #     azureSubscription: 'azure-subscription'
  #     azureResourceGroup: 'resource-group'
  #     kubernetesServiceEndpoint: 'kubernetes-service-endpoint'
  #     namespace: 'default'
  #     command: 'upgrade'
  #     chartType: 'FilePath'
  #     chartPath: './deployment/helm/charts'
  #     releaseName: 'assignment-release'
  #     overrideValues: 'image.repository=$(Build.Repository.Name)'
