env:
- name: ASPNETCORE_ENVIRONMENT
  value: Development

image:
  repository: 'derya1123581321/assignment'
  pullPolicy: Always
  tag: 'latest'

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70

resources:
  requests:
    cpu: "20m"
    memory: "256Mi"
  limits:
    cpu: "20m"
    memory: "256Mi"
